INSERT INTO keywords (id, keyword)VALUES(1,'Nebulas');
INSERT INTO keywords (id, keyword)VALUES(2,'Ethereum');
INSERT INTO keywords (id, keyword)VALUES(2,'Smart contract');
INSERT INTO keywords (id, keyword)VALUES(2,'Decentralized Application');
INSERT INTO keywords (id, keyword)VALUES(2,'Solidity');
INSERT INTO keywords (id, keyword)VALUES(2,'Proof of work');
INSERT INTO keywords (id, keyword)VALUES(2,'Distributed System');
INSERT INTO keywords (id, keyword)VALUES(2,'Ethereum VM');
INSERT INTO keywords (id, keyword)VALUES(2,'P2P Networking');
INSERT INTO keywords (id, keyword)VALUES(2,'Truffle');
INSERT INTO keywords (id, keyword)VALUES(2,'Ganache');
INSERT INTO keywords (id, keyword)VALUES(2,'Ethereum Virtual Machine(EVM)');
INSERT INTO keywords (id, keyword)VALUES(3,'Hyperledger');
INSERT INTO keywords (id, keyword)VALUES(3,'Distributed ledger frameworks');
INSERT INTO keywords (id, keyword)VALUES(3,'Smart Contract');
INSERT INTO keywords (id, keyword)VALUES(3,'Sawtooth');
INSERT INTO keywords (id, keyword)VALUES(3,'Iroha');
INSERT INTO keywords (id, keyword)VALUES(3,'Fabric');
INSERT INTO keywords (id, keyword)VALUES(3,'Burrow');
INSERT INTO keywords (id, keyword)VALUES(3,'Indy');
INSERT INTO keywords (id, keyword)VALUES(3,'Proof of Elapsed Time');
INSERT INTO keywords (id, keyword)VALUES(3,'Distributed Systems');
INSERT INTO keywords (id, keyword)VALUES(3,'Peer to peer networking');
INSERT INTO keywords (id, keyword)VALUES(4,'Public Chain Infrastructure');
INSERT INTO keywords (id, keyword)VALUES(5,'Smart Contract');
INSERT INTO keywords (id, keyword)VALUES(5,'Decentralized Application');
INSERT INTO keywords (id, keyword)VALUES(5,'Solidity');
INSERT INTO keywords (id, keyword)VALUES(5,'Ethereum');
INSERT INTO keywords (id, keyword)VALUES(5,'Hyperledger');
INSERT INTO keywords (id, keyword)VALUES(6,'dApp Backend');
INSERT INTO keywords (id, keyword)VALUES(6,'Ethereum');
INSERT INTO keywords (id, keyword)VALUES(6,'Nebulas');
INSERT INTO keywords (id, keyword)VALUES(6,'IPFS');
INSERT INTO keywords (id, keyword)VALUES(6,'Smart Contract');
INSERT INTO keywords (id, keyword)VALUES(7,'dApp Frontend');
INSERT INTO keywords (id, keyword)VALUES(7,'Web3');
INSERT INTO keywords (id, keyword)VALUES(7,'JavaScript');
INSERT INTO keywords (id, keyword)VALUES(7,'MetaMask');
INSERT INTO keywords (id, keyword)VALUES(7,'Port');
INSERT INTO keywords (id, keyword)VALUES(7,'Truffle');
INSERT INTO keywords (id, keyword)VALUES(7,'Solidity');
INSERT INTO keywords (id, keyword)VALUES(8,'IPFS/Storage/Network');
INSERT INTO keywords (id, keyword)VALUES(8,'Peer-to-peer hypermedia protocol');
INSERT INTO keywords (id, keyword)VALUES(8,'IPNS');
INSERT INTO keywords (id, keyword)VALUES(8,'FUSE');
INSERT INTO keywords (id, keyword)VALUES(8,'Decentralized Archiving');
INSERT INTO keywords (id, keyword)VALUES(8,'P2P content deliver');
INSERT INTO keywords (id, keyword)VALUES(9,'Industry Use Cases');
INSERT INTO keywords (id, keyword)VALUES(9,'Digital Identity');
INSERT INTO keywords (id, keyword)VALUES(9,'Tokenization');
INSERT INTO keywords (id, keyword)VALUES(9,'Inter-Organizational data management');
INSERT INTO keywords (id, keyword)VALUES(9,'Financial institutions');
INSERT INTO keywords (id, keyword)VALUES(9,'Audits');
INSERT INTO keywords (id, keyword)VALUES(9,'Regulatory compliance');
INSERT INTO keywords (id, keyword)VALUES(9,'Clearing and settlement');
INSERT INTO keywords (id, keyword)VALUES(9,'Automated governance');
INSERT INTO keywords (id, keyword)VALUES(9,'Health care records');
INSERT INTO keywords (id, keyword)VALUES(9,'Insurance');
INSERT INTO keywords (id, keyword)VALUES(9,'Notary');
INSERT INTO keywords (id, keyword)VALUES(9,'Digital Assets');
INSERT INTO keywords (id, keyword)VALUES(9,'Smart Contract');
INSERT INTO keywords (id, keyword)VALUES(9,'Digital voting');
INSERT INTO keywords (id, keyword)VALUES(9,'Distributed storage');
