DROP TABLE IF EXISTS `solutionmap`;
CREATE TABLE `solutionmap` (
  `solution_name` varchar(80) NOT NULL,  
  `step` int(11) NOT NULL,
  `step_name` varchar(200) NOT NULL,
  `step_description` text  NOT NULL,
  `step_url` varchar(300) NOT NULL,
  PRIMARY KEY (`solution_name`, `step`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `solutionmap` VALUES ('consensus', 1, 'Proof of Work(PoW)', 'A proof of work is a piece of data which is difficult (costly, time-consuming) to produce but easy for others to verify and which satisfies certain requirements.The main innovation that Satoshi Nakamoto introduced in his article is using so-called proof of work (POW) to create distributed trustless consensus and solve the double-spend problem. ', 'https://en.wikipedia.org/wiki/Proof-of-work_system');
INSERT INTO `solutionmap` VALUES ('consensus', 2, 'Proof of Stake(PoS)', 'Proof of Stake is a proposed alternative to Proof of Work. It is a type of algorithm by which [..] the creator of the next block is chosen via various combinations of random selection and wealth or age (i.e., the stake). Proof of Stake increased protection from a malicious attack on the network, and helps to alleviate Monopoly Problem.', 'https://en.wikipedia.org/wiki/Proof-of-stake');
INSERT INTO `solutionmap` VALUES ('consensus', 3, 'Delegated Proof of Stake(DPoS)', 'DPoS is a system in which a fixed number of elected entities (called block producers or witnesses) are selected to create blocks in a round-robin order. Block producers are voted into power by the users of the network, who each get a number of votes proportional to the number of tokens they own on the network (their stake) Alternatively, voters can choose to delegate their stake to another voter, who will vote in the block producer election on their behalf.Not only is DPoS a more democratic system, it is also more efficient and effective. The selection of block producers allows for the transactions to be validated in a matter of seconds, rather than the 10 minutes it takes the proof of work system employed by Bitcoin. For example, in the case of Lisk it currently only takes 10 seconds to validate a block of transactions.', 'https://medium.com/loom-network/understanding-blockchain-fundamentals-part-3-delegated-proof-of-stake-b385a6b92ef');
INSERT INTO `solutionmap` VALUES ('consensus', 4, 'Consensus Protocol', 'CONSENSUS  means that the nodes on the network agree on the same state of a blockchain, in a sense making it a self-auditing ecosystem.This is an absolutely crucial aspect of the technology, carrying out two key functions. Firstly, consensus protocols allow a blockchain to be updated, while ensuring that every block in the chain is true as well as keeping participants incentivized. Secondly, it prevents any single entity from controlling or derailing the whole blockchain system. The aim of consensus rules is to guarantee a single chain is used and followed.', 'https://lisk.io/academy/blockchain-basics/technologies-of-blockchain/consensus-protocols');

INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 1, "Basic of Ethereum","If you want to know what is Ethereum and how it works and what it can be used for , without going deep into the technical abyss, this guide is perfect for you.","https://blockgeeks.com/guides/ethereum/");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 2, "Practical blockchain solutions","You may have heard the terms “blockchain” and “smart contract” floating around, but what do they actually mean? In this tutorial, we’ll demystify the jargon, show you practical blockchain solutions, and give you direction on how to create an application that takes advantage of the blockchain.", "https://truffleframework.com/tutorials/ethereum-overview ");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 3, "Basics of ICO", "Initial coin offerings, or ICOs. Also known as 'token sales' this new fundraising phenomenon is being filed by a convergence of blockchain technology, new wealth, clever entrepreneurs, and crypto-investors who are backing blockchain-fueled ideas.","https://hbr.org/2017/03/what-initial-coin-offerings-are-and-why-vc-firms-care");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 4, "Token economics", "There is one assumption on which nearly all token economic models are based: people act upon incentives. This is based on incentive theory, a human behavioral theory that assumes behavior is motivated by a desire for reinforcement or incentives. In token economics, these incentives are the tokens themselves and they are used to motivate network members to behave to the benefit of the network.", "https://www.investinblockchain.com/token-economics/ ");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 5, "Create your first ICO", "How to create token and initial coin offering contracts using truffle + zeppelin solidity- Gustavo Guimaraes? Truffle is the de facto framework for creating smart contracts and decentralized applications. Zeppelin Solidity is a library that has extensive and well tested smart contracts that adhere to security best practices. In the smart contract world where a small bug can cost you money, it is good not to reinvent the wheel when there are trusted solutions out there.", "contracts-using-truffle-openzeppelin-1b7a5dae99b6 ");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 6, "Ethereum Pet Shope", "A tutorial on how to set up your Ethereum programming environment", "https://truffleframework.com/tutorials/pet-shop ");
INSERT INTO `solutionmap` VALUES ('create-icoe-use-thereum', 7, "Audit code for bugs and security", "BountyOne Decentralized Audits - A decentralized auditing platform that harnesses the best blockchain engineers and auditors", "https://bountyone.io/auditsLanding ");


INSERT INTO `solutionmap` VALUES ('build-DAPP', 1, 'Build Your First dApp', 'Build Your First dApp in 5 Quick Steps', 'https://itnext.io/build-your-first-blockchain-application-in-5-quick-steps-89ebb96adbfe');
INSERT INTO `solutionmap` VALUES ('build-DAPP', 2, 'Smart Contract in dApp', 'This one takes some setup and programming, but really covers smart contract in ethereu - The ultimate end-to-end tutorial to create and deploy a fully decentralized Dapp in ethereum', 'https://medium.com/@merunasgrincalaitis/the-ultimate-end-to-end-tutorial-to-create-and-deploy-a-fully-descentralized-dapp-in-ethereum-18f0cf6d7e0e');
INSERT INTO `solutionmap` VALUES ('build-DAPP', 3, 'How to Write upgradable smart contracts', 'An approach to upgrade contracts must be in the armor to prevent damage made by programming bugs after contract got deployed.','https://medium.com/quillhash/how-to-write-upgradable-smart-contracts-in-solidity-d8f1b95a0e9a');
INSERT INTO `solutionmap` VALUES ('build-DAPP', 4, 'Blockchain Web Development Tools', 'Top 7 blockchain web development tools used by blockchain web developers for both ethereum as well as bitcoin.','https://hackernoon.com/7-blockchain-web-development-tools-that-will-grow-your-stack-3d854f1cb9bf');

