INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'A Brief History of Blockchain','','https://hbr.org/2017/02/a-brief-history-of-blockchain',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'History of Blockchain','Video','https://www.youtube.com/watch?v=7Y3fWXA6d5k',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'The Promise of Blockchain Is a World Without Middlemen','The blockchain is a revolution that builds on another technical revolution so old that only the more experienced among us remember it: the invention of the database.','https://hbr.org/2017/03/the-promise-of-blockchain-is-a-world-without-middlemen',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Welcome to 3.0','Why the Internet (as we know it) is broken, and how the world will fix it, together.','https://medium.com/@ConsenSys/welcome-to-3-0-f4552fb02302',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Smart Contracts: The Blockchain Technology That Will Replace Lawyers','A beginners guide to smart contracts','https://blockgeeks.com/guides/smart-contracts/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Blockchain & Cyber Security','In this paper Deloitte’s global blockchain and cyber security experts from around the globe have joined forces to assess specifically the security of blockchain technology.','https://www2.deloitte.com/content/dam/Deloitte/ie/Documents/Technology/IE_C_BlockchainandCyberPOV_0417.pdf',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Exploring Continuous Token Models: Towards a Million Networks of Value.','I want to put forth new exploratory models for thinking about tokenizing protocols, decentralized applications & interest networks.','https://media.consensys.net/exploring-continuous-token-models-towards-a-million-networks-of-value-fff153175776',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Derivatives on Blockchain: Key Concepts','Derivative products, hedging mechanisms, and the road to stable tokens.','https://media.consensys.net/derivatives-on-blockchain-key-concepts-bbb5393e16a4',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'How Blockchain Is Helping Technology Get Its Soul Back','These humanitarian solutions are pointing us beyond the techlash and proving that more technology, not less, is the key to international relief.','https://media.consensys.net/how-blockchain-is-helping-technology-get-its-soul-back-a2d6cf96a272',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'A Future History of International Blockchain Standards','Blockchain and blockchain-related technologies are being rapidly invented to the point that it is difficult to define specifically which properties are necessary to constitute a blockchain. It may therefore seem far too early to meaningfully discuss the creation of international blockchain standards. This article will argue the opposite by summarising some existing international standards work related to blockchains, and propose directions for additional standards development that could meaningfully be explored in the near future without negatively impacting additional invention.','https://www.researchgate.net/publication/325896311_A_Future_History_of_International_Blockchain_Standards',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Introduction', 'Introduction', 'Blockchain at Berkley - Resources','Resources and presentations that where created by Berkley Students and faculty.','https://blockchain.berkeley.edu/resources/ ',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Security', 'If you understand Hash Functions, you will understand Blockchains','Hash functions are a fundamental part of blockchain technologies. If you understand hash functions, it will make understanding other concepts such as tamper proofing, digital fingerprints and provenance easier.','https://decentralize.today/if-you-understand-hash-functions-youll-understand-blockchains-9088307b745d',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Security', 'Blockchain Underpinnings: Hashing','A hash function, takes any input, and produces an output of a specific size. The process of applying a hash function to some data, is called hashing.','https://medium.com/@ConsenSys/blockchain-underpinnings-hashing-7f4746cbd66b',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Consensus', 'Proof of Work vs Proof of Stake: Basic Mining Guide','In this article, I will explain to you the main differences between Proof of Work vs Proof of Stake and I will provide you a definition of mining, or the process new digital currencies are released through the network.','https://blockgeeks.com/guides/proof-of-work-vs-proof-of-stake/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Consensus', 'Byzantine Fault Tolerance in a Distributed System','The object of Byzantine fault tolerance is to be able to defend against failures, in which components of a system fail in arbitrary ways, i.e., not just by stopping or crashing but by processing requests incorrectly, corrupting their local state, and/or producing incorrect or inconsistent outputs. The Byzantine failure models real-world environments in which computers and networks may behave in unexpected ways due to hardware failures, network congestion and disconnection, as well as malicious attacks.','http://sce.uhcl.edu/goodwin/Ceng5334/downLoads/byzantine.pdf',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Consensus', 'A Proof of Stake Design Philosophy','Systems like Ethereum (and Bitcoin, and NXT, and Bitshares, etc) are a fundamentally new class of cryptoeconomic organisms — decentralized, jurisdictionless entities that exist entirely in cyberspace, maintained by a combination of cryptography, economics and social consensus.','https://medium.com/@VitalikButerin/a-proof-of-stake-design-philosophy-506585978d51',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Network', 'What is a Peer-to-Peer (P2P) Network?','In its simplest form, a peer-to-peer (P2P) network is created when two or more PCs are connected and share resources without going through a separate server computer.','https://www.computerworld.com/article/2588287/networking/networking-peer-to-peer-network.html',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Network', 'Designing for Blockchain: What is Different and What is at Stake','How to design for trust around a “trustless” technology.','https://media.consensys.net/designing-for-blockchain-whats-different-and-what-s-at-stake-b867eeade1c9',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Network', 'TokenWork: Introducing the Token Utility Canvas (TUC)','A framework for developing technically and functionally sound tokens and business models.','https://media.consensys.net/tokenwork-introducing-the-token-utility-canvas-tuc-9a1f32979dc0',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Security', 'Cryptographic Identity in the Blockchain','Video','https://www.youtube.com/embed/fgSvXFZ1GuU?start=1005&end=1187&version=3',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Security', 'Bitcoin-Digital Signatures','Video','https://www.youtube.com/watch?v=Aq3a-_O2NcI&feature=youtu.be',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Infrastructure', 'Security', 'Guide: Hashing','A guide to hashing algorithms like those used in Ethereum.','https://media.consensys.net/guide-hashing-33dc0467c126',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin Developer Guide','Find detailed information about the Bitcoin protocol and its specifications','https://bitcoin.org/en/developer-guide#coinjoin',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin Mining Explained Like You are Five: Part 1 - Incentives','It’s fairly easy to use standard cryptographic tools, like digital signatures, to “prove” ownership of something. I can prove I own one bitcoin by presenting a valid digital signature. I can also sign over ownership of that bitcoin to you by attaching your bitcoin address to it before signing. The problem we run into, however, is that there is no way to know whether I also signed over ownership of that same coin to someone else (or even to another address controlled by myself) before transferring it to you. Since bitcoins are digital, they are not scarce and can be copied ad infinitum. Any digital currency that doesn’t tackle this “double spend” problem, will be destroyed by hyperinflation on day one.','https://chrispacia.wordpress.com/2013/09/02/bitcoin-mining-explained-like-youre-five-part-1-incentives/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin Mining Explained Like You are Five: Part 2 - Mechanics','In this post we will take more a technical look at the cryptography involved and how it is used to secure the network.','https://chrispacia.wordpress.com/2013/09/02/bitcoin-mining-explained-like-youre-five-part-2-mechanics/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin Explained Like You are Five: Part 3 - Cryptography','If you’re reading this, I’m going to assume you have limited knowledge of cryptography. So instead of jumping right into digital signatures, I’m going to start by providing a broad introduction to cryptography. Hopefully you’ll learn not just how Bitcoin works, but also how to stay safe on the internet by keeping your private information away from prying eyes.','https://chrispacia.wordpress.com/2013/09/07/bitcoin-cryptography-digital-signatures-explained/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin Explained Like You are Five: Part 4 - Securing Your Wallet',' I figured I would extend my Bitcoin ELI5 series with this post and detail a number of best practices that you can use to avoid this fate.','https://chrispacia.wordpress.com/2013/09/29/bitcoin-explained-like-youre-five-part-4-securing-your-wallet/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Learn', 'Bitcoin and Cryptocurrencies','Princenton video lecture','https://www.youtube.com/channel/UCNcSSleedtfyDuhBvOQzFzQ',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Bitcoin', 'Tools&Resources', 'Bitcoin GitHub','','https://github.com/bitcoin/bitcoin',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Hyperledger','Learn','Hyperledger Fabric resources', '', 'https://hyperledger-fabric.readthedocs.io/en/release-1.1/getting_started.html',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Hyperledger','Learn','Blockchain for Dummies', '', 'https://www.ibm.com/blockchain/what-is-blockchain',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Ethereum', 'Tools&Resources', 'ConsenSys/ethereum-developer-tools-list','GitHub Resources','https://github.com/ConsenSys/ethereum-developer-tools-list',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Ethereum', 'Tutorials', 'How to use MetaMask for Chrome','MetaMask is an Ethereum extension for your browser. It connects you to Ethereum applications (called dApps) easily and securely.','https://blog.ujomusic.com/how-to-use-metamask-for-chrome-f258e6034226',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Ethereum', 'Tutorials', 'Solidity','Community generated resource for ethereum development.','https://solidity.readthedocs.io/en/v0.4.23/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Ethereum', 'Tutorials', 'Top Dapp tutorials Series','Learn how to build Dapps from tutorial series and Stories on Ethereum, Neo, Nebulas and Eos — Dapps rule','https://medium.com/coinmonks/top-dapp-tutorial-series-2e70c0d79782',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('OtherProtocol', 'Other Protocol', 'An Introduction to IPFS','In some ways, this is similar to the original aims of the Web, but IPFS is actually more similar to a single bittorrent swarm exchanging git objects. IPFS could become a new major subsystem of the internet. If built right, it could complement or replace HTTP.','https://medium.com/@ConsenSys/an-introduction-to-ipfs-9bba4860abd0',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('OtherProtocol', 'Other Protocol', 'A Complete List of uPort Protocols, Libraries and Solutions','Want a complete list of uPort protocols, libraries and solutions? Congratulations! You’ve come to the right place.','https://medium.com/uport/a-complete-list-of-uports-protocols-libraries-and-solutions-63e9b99b9fd6',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'Crypto Tokens: A Breakthrough in Open Network Design','crypto tokens — a new way to design open networks that arose from the cryptocurrency movement that began with the introduction of Bitcoin in 2008 and accelerated with the introduction of Ethereum in 2014.','https://medium.com/@cdixon/crypto-tokens-a-breakthrough-in-open-network-design-e600975be2ef',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'A gentle introduction to self-sovereign identity','Self-sovereign identity is the concept that people and businesses can store their own identity data on their own devices, and provide it efficiently to those who need to validate it, without relying on a central repository of identity data.  It’s a digital way of doing what we do today with bits of paper.','https://bitsonblocks.net/2017/05/17/a-gentle-introduction-to-self-sovereign-identity/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'Perdiction Markets','Forget Bitcoin. The blockchain could reveal whats true today or tomorrow','https://www.wired.com/2017/03/forget-bitcoin-blockchain-reveal-whats-true-today-tomorrow/',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'Peer-to-Peer Trading: Introducing Swap: A Protocol for Decentralized Peer-to-Peer Trading on the Ethereum Blockchain','The two forces behind our design are decentralization and peer-to-peer. Decentralization allows users to exchange value in a “trustless” way rather than depending on the security, ethics, and diligence of a central entity.','https://blog.airswap.io/introducing-swap-a-protocol-for-decentralized-peer-to-peer-trading-on-the-ethereum-blockchain-d4058f3179cf',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'StabL Bringing Stable Tokens and Derivative Products to the Ethereum Blockchain','The problem with using ether as a currency, is that it is a currency whose price is variable. If this risk obstacle of volatile price were overcome, with the introduction of a cryptographic asset that tracks, for example, to USD, it would pave the way for massive acceleration of Ethereum adoption','https://blog.variabl.io/stabl-bringing-stable-tokens-and-derivative-products-to-the-ethereum-blockchain-df4d5eba89d9',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'Decentralized Storage: The Backbone of the Third Web','We will then look at the storage technologies that are likely to form its backbone: the decentralized storage network IPFS and it’s incentive platform Filecoin and Swarm, an emerging Ethereum oriented storage platform that uses IPFS.','https://media.consensys.net/decentralized-storage-the-backbone-of-the-third-web-d4bc54e79700',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('UseCases', 'Use Cases', 'The Blockchain Will Do to the Financial System What the Internet Did to Media','Even years into the deployment of the internet, many believed that it was still a fad. Of course, the internet has since become a major influence on our lives, from how we buy goods and services, to the ways we socialize with friends, to the Arab Spring, to the 2016 U.S. presidential election. Yet, in the 1990s, the mainstream press scoffed when Nicholas Negroponte predicted that most of us would soon be reading our news online rather than from a newspaper.','https://hbr.org/2017/03/the-blockchain-will-do-to-banks-and-law-firms-what-the-internet-did-to-media',NOW());

INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain Architecture Course','While currently in the beginning stages of deploying this technology, understanding the available platforms, hosting, associated technologies, languages and security is paramount to the success of any POC or enterprise deployment. Corporate Executives, decision makers, stakeholders and developers seeking to align their efforts with the technology need to be aware of the various aspects related to this technology and development.','https://www.theblockchainacademy.com/store/7BoyEE4C',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'GBA Specialist Certification Course','This credential is available to any member of the Government Blockchain Association (GBA) who has completed the five required courses and successfully passed the exam. Each day, the training is a mix of traditional course material delivery and hands-on service design workshops where attendees will break out into working sessions and apply the lessons taught. Attendees will design and develop solutions to real-world uses cases and projects. Project scenarios can come from attendees current challenges or a scenario can be provided as needed.','https://www.theblockchainacademy.com/p/gba-blockchain-specialist-certification-course',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain for Lawyers','The legal industry is undergoing profound changes, as the digital revolution takes its course. New technologies and innovative business models challenge the established position legal professionals have retained for centuries as sophisticated, high-earning advisors to every significant business transaction. With the advent of smart contract technology, business transactions of all kinds will experience a significant evolutionary step towards automation.','https://www.theblockchainacademy.com/store/VKNrZAnA',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain for Entreprise ','The outcome of this course is to provide individuals with a general overview of bitcoin and the blockchain. Attendees will learn more about what bitcoin is, its history, how to use bitcoin: storing bitcoin in a wallet, buying and selling bitcoin on an online exchange, as well as sending and receiving bitcoin from one person to another without the need for a trusted third party.','https://www.theblockchainacademy.com/store/o3322rA2',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain Security Workshop','This is a hands-on deep dive into the world of blockchain security delivered live.','https://www.theblockchainacademy.com/store/VbsTppA2',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Ethereum: Zero to dApp','This 2-weeks course is designed for web/app developers who wish to understand how to create and/or integrate Ethereum based apps. The course gives a top down view of all the important aspects in creating such an app and a basic overview to how the Ethereum blockchain works.','https://www.theblockchainacademy.com/store/vGLPakmq',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Smart Contracts Workshop','All you need is two days, to get started on how to create your own smart contracts! If you’re looking for an opportunity to learn what the fuss is all about, but never had the time to dive into it yourself, come to our weekend workshop.','https://www.theblockchainacademy.com/store/FBFKTG2t',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain Foundations','This ONLINE on-demand course is an introduction to the world of bitcoin, blockchain and distributed ledgers. We’ll cover the basics, look at how Bitcoin works under the hood, explore Bitcoin and blockchain’ s brief and fascinating history, and show you the practical usage of Bitcoin and blockchain technology.','https://www.theblockchainacademy.com/store/GVaPCSzc',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain & Bitcoin Intensive','This ONLINE on-demand course in a deeper look at the concepts that have been previously covered in the foundations course. Look under the hood and really get to grips with how the mining works and the bitcoin world.','https://www.theblockchainacademy.com/store/8b5qnidz',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain Development Decision Course','This ONLINE on-demand course introduces you to the decisions related to a blockchain deployment. Blockchain is becoming one of the most exciting technologies that is disrupting business and industries alike.','https://www.theblockchainacademy.com/store/iu2DyK7z',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'Blockchain and the Financial Sector Intensive','This immersive ONLINE on-demand course is designed individuals who understand the basics of digital currencies such as bitcoin and the blockchain technology, with a focus on adoption and use within the Financial Sector.','https://www.theblockchainacademy.com/store/5iQ22zQz',NOW());
INSERT INTO materials (type, subtype, name, description, link, created) VALUES('Training', 'Training Courses', 'The Blockchain Regulatory Environment','','https://www.theblockchainacademy.com/store/cg96zrnF',NOW());



